name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v examples/main.go

      - name: Run Unit tests
        env:
          ONFIDO_API_TOKEN: ${{ secrets.ONFIDO_API_TOKEN }}
          ONFIDO_WORKFLOW_ID: ${{ secrets.ONFIDO_WORKFLOW_ID }}
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...

      # - name: Install goveralls
      #   run: go install github.com/mattn/goveralls@latest
      #
      # - name: Send coverage
      #   env:
      #     COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      #     GIT_BRANCH: ${{ github.ref }}
      #   run: |
      #     goveralls -coverprofile=covprofile -service=github \
      #       -repotoken ${{ secrets.COVERALLS_TOKEN }} \
      #       -parallel -flagname="unit-tests"
